import pygame


class Images:
    gray = pygame.image.load('images/activeDots/gray.png'), pygame.image.load('images/activeDots/gray.png')
    red = pygame.image.load('images/activeDots/red.png'), pygame.image.load('images/disabledDots/red.png')
    blue = pygame.image.load('images/activeDots/blue.png'), pygame.image.load('images/disabledDots/blue.png')
    green = pygame.image.load('images/activeDots/green.png'), pygame.image.load('images/disabledDots/green.png')
    marine = pygame.image.load('images/activeDots/marine.png'), pygame.image.load('images/disabledDots/marine.png')
    yellow = pygame.image.load('images/activeDots/yellow.png'), pygame.image.load('images/disabledDots/yellow.png')
    pink = pygame.image.load('images/activeDots/pink.png'), pygame.image.load('images/disabledDots/pink.png')
    purple = pygame.image.load('images/activeDots/purple.png'), pygame.image.load('images/disabledDots/purple.png')
    orange = pygame.image.load('images/activeDots/orange.png'), pygame.image.load('images/disabledDots/orange.png')
    trans = pygame.image.load('images/graphics/transparent.png')
    motioned = pygame.image.load('images/graphics/motioned.png')
    restart = pygame.image.load('images/buttonIcons/restart.png')
    home = pygame.image.load('images/buttonIcons/home.png')
    record = pygame.image.load('images/buttonIcons/record.png')
    down = pygame.image.load('images/buttonIcons/down.png')
    up = pygame.image.load('images/buttonIcons/up.png')
    ok = pygame.image.load('images/buttonIcons/play.png')
    load = pygame.image.load('images/buttonIcons/load.png')
    save = pygame.image.load('images/buttonIcons/save2.png')
    empty = pygame.image.load('images/graphics/empty.png')
    cross = pygame.image.load('images/buttonIcons/cross.png')
    ai = pygame.image.load('images/icons/ai.png')
    man = pygame.image.load('images/icons/man.png')
    nx = pygame.image.load('images/icons/nx.png')
    ny = pygame.image.load('images/icons/ny.png')
