import pygame


class Images:
    gray = pygame.image.load('images/gray.png')
    red = pygame.image.load('images/red.png')
    blue = pygame.image.load('images/blue.png')
    green = pygame.image.load('images/green.png')
    marine = pygame.image.load('images/marine.png')
    yellow = pygame.image.load('images/yellow.png')
    pink = pygame.image.load('images/pink.png')
    purple = pygame.image.load('images/purple.png')
    orange = pygame.image.load('images/orange.png')
    trans = pygame.image.load('images/transparent.png')
    motioned = pygame.image.load('images/motioned.png')
    restart = pygame.image.load('images/restart.png')
    home = pygame.image.load('images/home.png')
    record = pygame.image.load('images/record.png')
    down = pygame.image.load('images/down.png')
    up = pygame.image.load('images/up.png')
    ok = pygame.image.load('images/ok.png')
    ai = pygame.image.load('images/ai.png')
    man = pygame.image.load('images/man.png')
    nx = pygame.image.load('images/nx.png')
    ny = pygame.image.load('images/ny.png')
